### ISSUE TITLE
Do Not Disturb mode

### ISSUE THREAD

**Issue by oneminch** [dailydotdev/daily-apps#157] opened 2020-09-21 15:20 UTC
When the "Do Not Disturb" mode is on, the new tab redirects user to the [Google](https://google.com) homepage. This isn't a very convenient feature as people like me use a different search engine by default. I personally use [DuckDuckGo](https://duckduckgo.com) as my search engine and [Firefox](https://firefox.com) as my browser. The default homepage without Daily is not a Google webpage. It's a local page (about:newtab). Is there a way Daily could redirect to the browsers default new tab page? If not at least allow user to set the page URL in a setting to further customize it?

**Comment by idoshamun** [comment] 2020-09-21 17:40
Thanks for reaching out!
Indeed we did some kind of a workaround to implement the Do Not Disturb mode.
Unfortunately, we cannot fetch the home page settings of your browser.
The only way is to manually set the URL you would like to see when DND is enabled. 
Currently, it is not supported by daily.dev extension.

I'm closing this issue as it's a duplicate of https://github.com/dailydotdev/daily/issues/103

**Closed by idoshamun** 2020-09-21 17:40 UTC
